name: Demo
runs:
  using: "composite"
  steps:
    - name: Setup conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        channels: conda-forge

    - name: Check for activated environment
      run: |
        echo $CONDA_PREFIX
        conda info
      shell: bash -l {0}
