name: "Demo"
runs:
  using: "composite"
  steps:
    - name: Setup conda environment
      uses: conda-incubator/setup-miniconda@v2

    - name: Export CONDA_PREFIX variable
      run: |
        echo $CONDA_PREFIX
        conda info
