name: "Set up python and conda environment"
description: 'Greet someone'
outputs:
  cache-hit:
    description: "Whether a cache hit was found"
    value: ${{ steps.condacache.outputs.cache-hit }}
runs:
  using: "composite"
  steps:
    - name: Set up python
      uses: actions/setup-python@v2
      with:
          python-version: 3.9

    - name: Get current week
      run: echo "WEEK=$(date +%U)" >> $GITHUB_ENV
      shell: bash -l {0}

    - name: Setup conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
          activate-environment: source-env
          auto-update-conda: true
          channels: conda-forge

    - name: Export CONDA_PREFIX variable
      run: echo "CONDA_PREFIX=$CONDA_PREFIX" >> $GITHUB_ENV
      shell: bash -l {0}

    - name: Restore conda environment cache
      uses: actions/cache@v2
      with:
        path: ${{ env.CONDA_PREFIX }}
        key: win-py3.9-test-sdist-${{ env.WEEK }}-${{ hashFiles('**/requirements*.txt') }}
      id: condacache