name: Set up GCP and deploy artifacts
inputs:
  credentials_json: "GCP credentials JSON to pass to google-github-actions/auth"
    description: "The python version to use"
    required: true
runs:
  using: composite
  steps:
    - name: Authenticate GCP
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ inputs.credentials_json }}

    - name: Set up GCP
      uses: google-github-actions/setup-gcloud@v0

    - name: Deploy artifacts to GCS
      if: github.event_name != 'pull_request'
      shell: bash
      run: make GSUTIL="gsutil" deploy # setup-gcloud action adds 'gsutil' to the PATH
