name: "Set up python and conda environment"
inputs:
  key:
    description: "Unique key to identify the cache to create/restore"
    required: false
    default: ""
outputs:
  cache-hit:
    description: "Whether a cache hit was found"
    value: ${{ steps.condacache.outputs.cache-hit }}
runs:
  using: "composite"
  steps:
    # don't need to run setup-python because we'll always use the
    # conda-managed python that'll be installed into this environment
    - name: Setup conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        channels: conda-forge

    - name: Set environment variables
      run: |
        echo "WEEK=$(date +%U)" >> $GITHUB_ENV
        echo "CONDA_PREFIX=$CONDA_PREFIX" >> $GITHUB_ENV
      shell: bash -l {0}

    - name: Restore conda environment cache
      uses: actions/cache@v2
      with:
        path: ${{ env.CONDA_PREFIX }}
        key: ${{ inputs.key }}-${{ env.WEEK }}-${{ hashFiles('**/requirements*.txt') }}
      id: condacache
