name: "Set up python and conda environment"
inputs:
  python-version:
    description: "Version of python to use"
    required: true
outputs:
  cache-hit:
    description: "Whether a cache hit was found"
    value: ${{ steps.condacache.outputs.cache-hit }}
runs:
  using: "composite"
  steps:
    - name: Set up python
      uses: actions/setup-python@v2
      with:
          python-version: ${{ inputs.python-version }}

    - name: Setup conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        channels: conda-forge

    - name: Set environment variables
      run: |
        echo "WEEK=$(date +%U)" >> $GITHUB_ENV
        echo "CONDA_PREFIX=$CONDA_PREFIX" >> $GITHUB_ENV
      shell: bash -l {0}

    - name: Restore conda environment cache
      uses: actions/cache@v2
      with:
        path: ${{ env.CONDA_PREFIX }}
        key: win-${{ inputs.python-version }}-test-sdist-${{ env.WEEK }}-${{ hashFiles('**/requirements*.txt') }}
      id: condacache
