name: Build and package electron application

on: [push, pull_request]

jobs:
  build-application:
    name: "Build and package electron application"
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: install environment
      run: npm install
    
    - name: build production code
      run: npm run build
    
    - name: package application
      run: npm run package
      env:
        CI: true

    - name: Upload application artifact
      uses: actions/upload-artifact@v2-preview
      with:
        name: InVEST-desktop-${{ matrix.os-version }}
        path: dist/**/invest-electron*
