name: Build and Release

on: [push, pull_request]

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [12.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Download invest binaries
      shell: bash
      run: |
        npm run prebuilt-invest ${{ matrix.os }}
        unzip ./build/binaries.zip -d ./build
        rm binaries.zip

    - name: Build & Release Electron application
      uses: samuelmeuli/action-electron-builder@v1
      with: 
        github_token: ${{ secrets.github_token }}
        # If the commit is tagged with a version (e.g. "v1.0.0"),
        # release the app after building
        release: ${{ startsWith(github.ref, 'refs/tags/v') }}
    
    - name: Upload installer artifacts
      uses: actions/upload-artifact@v2-preview
      with:
        name: invest-desktop-${{ matrix.os }}
        path: dist/invest-desktop_*
