name: Build, Test Binaries, & Release

on: [push, pull_request]

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        node-version: [12.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: NPM Install
      run: npm install

    - name: Fetch InVEST Binaries
      shell: bash
      run: npm run fetch-invest

    - name: Build & Release Electron application
      uses: samuelmeuli/action-electron-builder@v1
      if: ${{ always() }}
      with:
        build_script_name: build
        args: -c.extraMetadata.main=build/main.js
        github_token: ${{ secrets.github_token }}
        # If the commit is tagged with a version (e.g. "v1.0.0"),
        # release the app after building
        release: ${{ startsWith(github.ref, 'refs/tags/v') }}

      # Also run all tests on the build dir code?
    - name: Test flask app binaries
      shell: bash -l {0}
      run: npm run test-flask-app

    - name: Test electron app with puppeteer
      uses: GabrielBB/xvfb-action@v1
      if: matrix.os != 'macos-latest'
      with:
        run: npm run test-electron-app
    
    - name: Upload installer artifacts
      uses: actions/upload-artifact@v2-preview
      if: ${{ always() }}
      with:
        name: invest-workbench-${{ matrix.os }}
        path: dist/invest-workbench_*

    - name: Set up GCP
      # Secrets not available in PR so don't use GCP.
      if: github.event_name != 'pull_request'
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
          version: '281.0.0'
          service_account_key: ${{ secrets.GOOGLE_SERVICE_ACC_KEY }}

    - name: Set env var for deploy bucket
      shell: bash
      # If this is a release, don't include the commit hash
      run: |
        echo "GIT_REV=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "BUCKET=$([ env.GITHUB_ACTOR == 'natcap' ] \
          && echo 'gs://releases.naturalcapitalproject.org' \
          || echo 'gs://natcap-dev-build-artifacts/{{ env.GITHUB_ACTOR }}' \
          )" >> $GITHUB_ENV

    - name: Deploy artifacts to GCS
      # Secrets not available in PR so don't use GCP.
      # We only want to upload artifacts to a release object in a release.
      if: github.event_name != 'pull_request'
      run: |
        echo "${{ env.BUCKET }}/invest-workbench/${{ env.VERSION }}_${{ env.GIT_REV }}"
        gsutil -m rsync dist/invest-workbench* "${{ env.BUCKET }}/invest-workbench/${{ env.VERSION }}_${{ env.GIT_REV }}"
