name: Build, Test Binaries, & Release

on: [push, pull_request]

defaults:
  run:
    shell: bash -l {0}

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        node-version: [12.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # fetch complete history

    - name: Fetch git tags
      run: git fetch origin +refs/tags/*:refs/tags/*

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: NPM Install
      run: npm install

    - name: Fetch InVEST Binaries
      run: npm run fetch-invest

    - name: Run the build script
      run: npm run build

    - name: Set up Python for gsutil
      # gsutil requires a python, which is not included on Windows
      if: github.event_name != 'pull_request' && matrix.os == 'windows-latest'
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Set up GCP
      # Secrets not available in PR so don't use GCP.
      if: github.event_name != 'pull_request'
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
          version: '281.0.0'
          service_account_key: ${{ secrets.GOOGLE_SERVICE_ACC_KEY }}

    - name: Code-signing setup for macOS
      if: matrix.os == 'macos-latest'
      shell: bash
      env:
        P12_FILE_PATH: ~/Downloads/stanford_cert.p12
        KEYCHAIN_NAME: codesign_keychain
        KEYCHAIN_PASS: ${{ secrets.MAC_KEYCHAIN_PASS }}
        CERT_KEY_PASS: ${{ secrets.STANFORD_CERT_KEY_PASS }}

      run: |
        gsutil cp gs://stanford_cert/Stanford-natcap-code-signing-cert-expires-2024-01-26.p12 $P12_FILE_PATH 

        bash ./scripts/setup_macos_keychain.sh 

        # these env variables tell electron-builder to do code signing
        echo "CSC_KEYCHAIN=$KEYCHAIN_NAME" >> $GITHUB_ENV
        echo "CSC_NAME='Stanford University'" >> $GITHUB_ENV
        echo "CSC_KEY_PASSWORD=${{ secrets.STANFORD_CERT_KEY_PASS }}" >> $GITHUB_ENV
        echo "CSC_IDENTITY_AUTO_DISCOVERY=false" >> $GITHUB_ENV
       

    - name: Code-signing setup for Windows
      if: matrix.os == 'windows-latest'
      env:
        P12_FILE: Stanford-natcap-code-signing-cert-expires-2024-01-26.p12
        CLOUDSDK_PYTHON: ${{env.pythonLocation}}\python.exe
      run: |
        gsutil cp gs://stanford_cert/$P12_FILE ~/$P12_FILE

        # all these variables are used by electron-builder
        echo "CSC_LINK=~/$P12_FILE" >> $GITHUB_ENV
        echo "CSC_KEY_PASSWORD=${{ secrets.STANFORD_CERT_KEY_PASS }}" >> $GITHUB_ENV
        echo "CSC_IDENTITY_AUTO_DISCOVERY=false" >> $GITHUB_ENV

    - name: Run electron-builder
      env:
        GH_TOKEN: env.GITHUB_TOKEN
        DEBUG: electron-builder
      run: npm run dist

      # Also run all tests on the build dir code?
    - name: Test flask app binaries
      run: npm run test-flask-app

    - name: Test electron app with puppeteer
      uses: GabrielBB/xvfb-action@v1
      if: matrix.os != 'macos-latest'
      continue-on-error: true
      with:
        run: npm run test-electron-app
    
    - name: Upload installer artifacts to github
      uses: actions/upload-artifact@v2.2.1
      with:
        name: invest-workbench-${{ matrix.os }}
        path: dist/invest-workbench_*

    # Nothing below here runs on pull requests because we use github secrets
    # to authenticate for GCP and they are not accessible in pull request workflows.
    - name: Set variables for GCS deploy target
      if: github.event_name != 'pull_request'
      run: |
        echo "VERSION"=$(grep VERSION electron-builder.env | cut -d '=' -f2) >> $GITHUB_ENV
        echo "BUCKET=$([ ${{ github.repository_owner }} == 'natcap' ] \
          && echo 'gs://releases.naturalcapitalproject.org/invest-workbench' \
          || echo 'gs://natcap-dev-build-artifacts/invest-workbench/${{ github.repository_owner }}' \
          )" >> $GITHUB_ENV

    - name: Deploy artifacts to GCS - Windows
      if: github.event_name != 'pull_request' && matrix.os == 'windows-latest'
      env:
        CLOUDSDK_PYTHON: ${{env.pythonLocation}}\python.exe
      run: |
        gsutil -m rsync dist/ "${{ env.BUCKET }}/${{ env.VERSION }}/"

    - name: Deploy artifacts to GCS - macOS
      if: github.event_name != 'pull_request' && matrix.os == 'macos-latest'
      run: |
        gsutil -m rsync dist/ "${{ env.BUCKET }}/${{ env.VERSION }}/"
