name: Demo

on:
    push:
    pull_request:

defaults:
  run:
    shell: bash -l {0}

jobs:
  demo1:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up conda environment
        uses: conda-incubator/setup-miniconda@v2

      - name: Check for activated environment
        run: |
          echo $CONDA_PREFIX
          conda info

  demo2:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Use custom action
        uses: ./.github/actions/demo
