name: Run jest tests in NodeJS

on: [push, pull_request]

jobs:
  run-tests:
    name: "run jest tests"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: install environment
      run: npm install

    - name: Download invest binaries
      shell: bash
      # "-- <arg>" in run passes the arg through to the script
      run: |
        npm run prebuilt-invest -- ${{ runner.os }}
        unzip ./build/binaries.zip -d ./build
        rm ./build/binaries.zip

    - name: run tests
      run: npm test
      env:
        CI: true
        INVEST: ./build/invest/invest
        SERVER: ./build/invest/server
