name: Run integration tests in NodeJS

on: [push, pull_request]

jobs:
  run-tests:
    name: "run integration tests"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: install environment
      run: yarn install

    - name: Fetch InVEST Binaries
      run: yarn run fetch-invest

    - name: run tests
      run: yarn test
      env:
        CI: true
