name: test workflow trigger

on:
  # this workflow will run any time any PR into main is closed
  pull_request:
    types:
      - closed

jobs:
  finalize-and-tag:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.head_ref }}
          echo ${{ startsWith(github.head_ref, 'autorelease') }}
          echo ${{ github.event.pull_request }}
          echo ${{ github.event.pull_request.merged }}
